apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
spec:
  scaleTargetRef:
    apiVersion: extension/v1beta1
    kind: Deployment
    name: wordpress
minReplicas: 2
maxReplicas: 5
targetCPUUtilizationPercentage: 50

